=== starseeker/stepmod_mirror/dtd/projmg/issues.dtd
<!--
This set of declarations defines issues raised against a module.
Each module can have a number of files of issues against the module.
-->
<!-- This file was developed by Eurostep and supplied to NIST under contract.
     Authors:
	Rob Bodington
-->
<!--                    descriptive text                           -->
<!ENTITY % desctext SYSTEM "../text.ent">
%desctext;
<!ENTITY % description.content "%text-elts; | %block-elts; | %single-block-elts; ">
<!-- Each issue file consists of a single issues element -->
<!ELEMENT issues (issue*)>
<!ATTLIST issues
	module CDATA #REQUIRED
>

<!-- 
        The issue being raised against a module.
        If the type identifies the XML primary XML element that the issue
        is against:

        arm arm_lf mim mim_lf 
          then the issue is against express so the linkend attribute is 
          the identification of the express construct. The value is a
          structured string:
           <schema>.<entity|type|function|procedure|constant>.<attribute>|wr:<whererule>|ur:<uniquerule> 
           e.g.  work_order_arm.activity.name

        armexpg_lf mimexpg_lf
         then the issue is against an expressG diagrams.
         The linkend attribute indicates the expressg file

        mapping_table
         Then the issue is a against the mapping specification.
         the linkend attribute is the identification of the mapping spec.
         This is defined by flattening the element nodes.
         i.e. deleting all <> and "          
         The attributes entity, attribute and assertion_to should be
         specified. Use the = sign but deleting all "
         e.g.
          ae entity=Assigned_document_property 
         e.g
          ae entity=Product_design_to_individual aa attribute=individual_product assertion_to=Product_as_individual

        ballot
         This is the  ballot in which the issues was raised (if it was)
         e.g. "PLCS DIS ballot"
        
        ballot_comment_id
         This is the ID for the issue in the ballot. If the ballot issue results in a SEDS, the                issue ID will become the SEDS id, therefore, may get renumbered to. The
        ballot_comment_id is used to retain the original ballot comment id for auditing purposes.
-->
<!ELEMENT issue (description, comment*)>
<!ATTLIST issue
	id CDATA #REQUIRED
        type (general | keywords | contacts | purpose | inscope | outscope
| normrefs | definition | abbreviations | arm | armexpg | arm_lf |
armexpg_lf | mapping_table | mim  | mimexpg | mim_lf | mimexpg_lf | usage_guide | bibliography)  "general"
	linkend CDATA #IMPLIED  
        category (editorial | technical | minor_technical | major_technical | repository) "editorial"
	by CDATA #REQUIRED
	date CDATA #REQUIRED
        status (open | closed) "open"   
	seds (yes | no) "no" 
        ballot_comment (yes | no) "no"
        ballot CDATA #IMPLIED
        ballot_comment_id CDATA #IMPLIED
        resolution (accept | reject) "accept"
        member_body (AD | AE | AF | AG | AI | AL | AM | AN | AO | AQ | 
                     AR | AS | AT | AU | AW | AZ | BA | BB | BD | BE | 
                     BF | BG | BH | BI | BJ | BM | BN | BO | BR | BS | 
                     BT | BV | BW | BY | BZ | CA | CC | CD | CF | CG | 
                     CH | CI | CK | CL | CM | CN | CO | CR | CU | CV | 
                     CX | CY | CZ | DE | DJ | DK | DM | DO | DZ | EC | 
                     EE | EG | EH | ER | ES | ET | FI | FJ | FK | FM | 
                     FO | FR | GA | GB | GD | GE | GF | GH | GI | GL | 
                     GM | GN | GP | GQ | GR | GS | GT | GU | GW | GY | 
                     HK | HM | HN | HR | HT | HU | ID | IE | IL | IN | 
                     IO | IQ | IR | IS | IT | JM | JO | JP | KE | KG | 
                     KH | KI | KM | KN | KP | KR | KW | KY | KZ | LA | 
                     LB | LC | LI | LK | LR | LS | LT | LU | LV | LY | 
                     MA | MC | MD | MG | MH | MK | ML | MM | MN | MO | 
                     MP | MQ | MR | MS | MT | MU | MV | MW | MX | MY | 
                     MZ | NA | NC | NE | NF | NG | NI | NL | NO | NP | 
                     NR | NU | NZ | OM | PA | PE | PF | PG | PH | PK | 
                     PL | PM | PN | PR | PS | PT | PW | PY | QA | RE | 
                     RO | RU | RW | SA | SB | SC | SD | SE | SG | SH | 
                     SI | SJ | SK | SL | SM | SN | SO | SR | ST | SV | 
                     SY | SZ | TC | TD | TF | TG | TH | TJ | TK | TL | 
                     TM | TN | TO | TR | TT | TV | TW | TZ | UA | UG | 
                     UK |UM | US | UY | UZ | VA | VC | VE | VG | VI | 
                     VN |VU | WF | WS | YE | YT | YU | ZA | ZM | ZW) #IMPLIED
>

<!-- Status of the issue -->
<!ELEMENT comment (description)>
<!ATTLIST comment
	by CDATA #REQUIRED
	date CDATA #REQUIRED
>
<!ELEMENT description (%text-elts; | %block-elts; | %single-block-elts;)*>

=== starseeker/stepmod_mirror/data/modules/assembly_physical_interface_requirement/dvlp/issues.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: issues.xml,v 1.2 2005/01/20 13:04:31 kovaliovas Exp $ -->
<?xml-stylesheet type="text/xsl" href="../../../../xsl/projmg/issues_file.xsl"?>
<!DOCTYPE issues SYSTEM "../../../../dtd/projmg/issues.dtd">
<issues module="assembly_physical_interface_requirement">

<!--
Description of how the issues files is given in: stepmod\help\issues.htm
 id - an identifer of the isssue unique to this file
 type - the primary XML element in module.xml that the issue is against.
        Either: 
            general | keywords | contacts | purpose |
            inscope | outscope | normrefs | definition |
            abbreviations | arm | armexpg | arm_lf |
            armexpg_lf | mapping_table | mim  | mimexpg |
            mim_lf | mimexpg_lf | usage_guide | bibliography
 linkend - the target of the comment 
 category - editorial | minor_technical | major_technical | repository 
 by - person raising the issue
 date - date issue raised yy-mm-dd
 status - status of issue. Either "open" or "closed"
 seds - if "yes" then the issue has been raised as a SEDS.
        The id should be the id of the SEDS in the SC4 database

Comment - is a comment raised by someone about the issue

<issue
  id=""
  type=""
  linkend=""
  category=""
  by=""
  date=""
  status="open"
  seds="no">
  <description>

  </description>

<comment
   by="" 
   date="">
<description>
</description>
</comment>
 </issue>
-->

<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!-- +++++++++++++++++++   ISSUES                  ++++++++++++++ -->
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<issue
  id="1"
  type="arm"
  linkend="Assembly_physical_interface_requirement_arm.Protocol_requirement_allocation_to_part_terminal.wr:WR1"
  category="minor_technical"
  by="Viktoras Kovaliovas"
  date="2004-21-22"
  status="open"
  seds="no">
  <description>
  	The WR refers a non-existing attribute "requirement_assignment.assigned_requirement.reference_protocol".
  </description>
<comment
   by="T. Thurman" 
   date="2005-01-06">
<description>
the rule should be:
  WR1: EXISTS (assigned_requirement_property.reference_protocol);
</description>
</comment>
<comment
   by="T. Thurman" 
   date="2005-01-015">
<description>
updated express.  xml needs to be updated.
</description>
</comment>
 </issue>

<issue
  id="2"
  type="arm"
  linkend="Assembly_physical_interface_requirement_arm.Protocol_requirement_allocation_to_part_terminal.wr:WR2"
  category="minor_technical"
  by="Viktoras Kovaliovas"
  date="2004-21-22"
  status="open"
  seds="no">
  <description>
  	The WR refers a non-existing attribute "requirement_assignment.assigned_requirement.reference_protocol".
  </description>
<comment
   by="T. Thurman" 
   date="2005-01-06">
<description>
the rule should be:
      WR2 : protocol_signal IN assigned_requirement_property.reference_protocol.host_functional_definition\functional_unit_usage_view.access_mechanism;
</description>
</comment>
<comment
   by="T. Thurman" 
   date="2005-01-015">
<description>
updated express.  xml needs to be updated.
</description>
</comment>
 </issue>

<issue
  id="3"
  type="arm"
  linkend="Assembly_physical_interface_requirement_arm.Mating_connector_termination.signal_definition"
  category="major_technical"
  by="V. Kovaliovas"
  date="2005-01-12"
  status="closed"
  seds="no">
  <description>
The top level query used here returns Requirement_assignment, not the Requirement_view_definition.
  </description>
<comment
   by="T. Thurman" 
   date="2005-01-015">
<description>
I don't understand what you mean by top level query.
I traced the path of the query and the function and it looks ok to me.
(There may be a problem with the function parameter type of
requirement_asigned_item (I don't recall that it is valid to use a
SELECT type in a function parameter.))
I need more specifics.
</description>
</comment>

<comment
   by="V. Kovaliovas" 
   date="2005-01-20">
<description>
The issue was raised against the previous version of implementation, that used inline
"coding" instead of function. I have reviewed the function and it looks like to
be correct. I am closing this issue.
</description>
</comment>
 </issue>
</issues>
