=== starseeker/stepmod_mirror/publication/dtd/p1000_publication_index.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
        $Id: p1000_publication_index.dtd,v 1.9 2013/01/19 18:32:10 thomasrthurman Exp $
        Author:  Rob Bodington, Eurostep Limited
        Owner:   Developed by Eurostep http://www.eurostep.com 
        Purpose: DTD for publication indices        
-->

<!--                    descriptive text                           -->
<!ENTITY % desctext    SYSTEM "../../dtd/text.ent">
%desctext;

<!--                    Contacts                           -->
<!ENTITY % contacts    SYSTEM "../../dtd/contacts.ent">
%contacts;


<!ELEMENT description (%description.content;)*>

<!ELEMENT part1000.publication_index (description?, contacts, resource_docs?, modules?, deleted.modules?, deleted.resource_docs?)>
<!ATTLIST part1000.publication_index
	name CDATA #REQUIRED
    wg.number.publication_set CDATA #REQUIRED
    wg.number.publication_set_comments CDATA #IMPLIED
	date.iso_submission CDATA #REQUIRED
	date.iso_publication CDATA #REQUIRED
	sc4.working_group NMTOKEN #REQUIRED
>
<!ELEMENT resource_docs (resource_doc+)>
<!ELEMENT resource_doc EMPTY>
<!ATTLIST resource_doc
	name CDATA #REQUIRED
>

<!ELEMENT deleted.modules (module+)>
<!ELEMENT deleted.resource_docs (resource_doc+)>

<!ELEMENT modules (module+)>
<!ELEMENT module EMPTY>
<!ATTLIST module
	number CDATA #IMPLIED
	name CDATA #REQUIRED
	team CDATA #REQUIRED
	version CDATA #IMPLIED
	arm.change (y | n) "n"
	mim.change (y | n) "n"
>

=== starseeker/stepmod_mirror/publication/part1000/CR00007/publication_index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE part1000.publication_index SYSTEM "../../dtd/p1000_publication_index.dtd">
<!-- 
$Id: publication_index.xml,v 1.1 2010/09/13 02:45:50 fumikitanaka Exp $
  Author:  Rob Bodington, Eurostep Limited
  Owner:   Developed by Eurostep Limited http://www.eurostep.com
  Purpose: A listing of modules to be published as a Part 1000 change request
           Note - to generate an ant build for this package, run:
              ant -buildfile buildbuild.xml
           This will create the build.xml file.
           Then run: 
              ant all
           to create the HTML files of the individual modules
           See: readme.txt for details

     publication_index has the following attributes
           name
               The name of the publication set.
           wg.number.publication_set 
               The WG number for the publication set. 
               It should be an integer. 
           wg.number.publication_set_comments 
               The WG number for the addressed ballot comments
           date.iso_submission
               The date the set of parts were submitted to ISO
           date.iso_publication
               The date the set of parts were published by ISO           
-->
<part1000.publication_index
  name="CR00007"
  wg.number.publication_set=""
  wg.number.publication_set_comments=""
  date.iso_submission=""
  date.iso_publication="2010-99-07">

  <description>
    The modules that are to be added to Part1000 as part of 
    change request CR00007
    
    The STEPmod CVS repository shoudl be tagged as: CR00007
    before submitting the change request
  </description>

  <contacts>
    <projlead ref="hiroyuki.hiraoka"/>
    <editor ref="fumiki.tanaka"/>
  </contacts>

  <!-- The list of modules to be published as individual ISO parts and include in part1000 -->
  <!-- Only add the module once -->
  <modules>
    <!-- START: new PDQ modules, all ed 1  -->
    <module name="product_data_quality_definition" team="ap242"/>
    <module name="product_data_quality_criteria" team="ap242"/>
    <module name="product_data_quality_inspection_result" team="ap242"/>
    <module name="shape_data_quality_criteria" team="ap242"/>
    <module name="shape_data_quality_inspection_result" team="ap242"/>
    <module name="Composite_surface" team="ap242"/>                 
    <!-- END: PDQ modules -->

    <!-- Start: Other affected modules -->
    <module name="B_spline_geometry" team="ap242"/>                 <!-- ed 2, renamed schemas -->
    <module name="Basic_curve" team="ap242"/>                       <!-- ed 4 -->
    <module name="Basic_geometry" team="ap242"/>                    <!-- ed 5 -->
    <module name="Geometric_constraints" team="ap242"/>             <!-- ed 2 -->
    <module name="Geometrically_bounded_surface" team="ap242"/>     <!-- ed x -->
    <module name="Manifold_surface" team="ap242"/>                  <!-- ed x -->
    <module name="Topologically_bounded_surface" team="ap242"/>     <!-- ed x -->
    <!-- End: Other affected modules -->

   </modules>

</part1000.publication_index>

=== starseeker/stepmod_mirror/publication/part1000/CR00008/publication_index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE part1000.publication_index SYSTEM "../../dtd/p1000_publication_index.dtd">
<!-- 
$Id: publication_index.xml,v 1.1 2010/09/21 21:40:23 lothartklein Exp $
  Author:  Rob Bodington, Eurostep Limited
  Owner:   Developed by Eurostep Limited http://www.eurostep.com
  Purpose: A listing of modules to be published as a Part 1000 change request
           Note - to generate an ant build for this package, run:
              ant -buildfile buildbuild.xml
           This will create the build.xml file.
           Then run: 
              ant all
           to create the HTML files of the individual modules
           See: readme.txt for details

     publication_index has the following attributes
           name
               The name of the publication set.
           wg.number.publication_set 
               The WG number for the publication set. 
               It should be an integer. 
           wg.number.publication_set_comments 
               The WG number for the addressed ballot comments
           date.iso_submission
               The date the set of parts were submitted to ISO
           date.iso_publication
               The date the set of parts were published by ISO           
-->
<part1000.publication_index
  name="CR00008"
  wg.number.publication_set="3"
  wg.number.publication_set_comments=""
  date.iso_submission="2010-12-31"
  date.iso_publication="2010-12-31">

  <description>
    The modules that are to be added to Part1000 as part of 
    change request CR00008
  </description>

  <contacts>
    <projlead ref="hiroyuki.hiraoka"/>
    <editor ref="fumiki.tanaka"/>
  </contacts>

  <!-- resources
    p42 "geometric_and_topological_representation" ed4 
  -->

  <!-- The list of modules to be published as individual ISO parts and include in part1000 -->
  <!-- Only add the module once -->
  <modules>
    <!-- START: new PDQ modules, all ed 1  -->
    <module name="product_data_quality_definition" team="ap242"/>
    <module name="product_data_quality_criteria" team="ap242"/>
    <module name="product_data_quality_inspection_result" team="ap242"/>
    <module name="shape_data_quality_criteria" team="ap242"/>
    <module name="shape_data_quality_inspection_result" team="ap242"/>
    <!-- END: PDQ modules -->

    <!-- Start: Other required modules -->
    <module name="Composite_surface" team="ap242"/>                 
    <module name="B_spline_geometry" team="ap242"/>                 <!-- ed 2, renamed schemas -->
    <module name="Basic_curve" team="ap242"/>                       <!-- ed 4 -->
    <module name="Basic_geometry" team="ap242"/>                    <!-- ed 5 -->
    <module name="Geometrically_bounded_surface" team="ap242"/>     <!-- ed x -->
    <module name="Manifold_surface" team="ap242"/>                  <!-- ed x -->
    <module name="Topologically_bounded_surface" team="ap242"/>     <!-- ed x -->
    <module name="Value_with_unit" team="ap242"/>     <!-- ed x -->
    <!-- End: Other required modules -->

    <!-- START: parameterization and constraint modules -->
     <module name="explicit_constraints" team="ap242"/>
     <module name="geometric_constraints" team="ap242"/>
     <module name="parameterization_and_variational_representation" team="ap242"/>
     <module name="sketch" team="ap242"/>
     <module name="expression" team="ap242"/>
     <module name="generic_expression" team="ap242"/>
     <module name="numeric_expression" team="ap242"/>
     <module name="elmentary_function" team="ap242"/>
     <module name="numeric_function" team="ap242"/>
    <!-- END: parameterization and constraint modules -->

   </modules>


</part1000.publication_index>
