=== starseeker/stepmod_mirror/dtd/description.dtd
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Rob Bodington (Eurostep Limited) -->
<!--
     $Id: express.dtd,v 1.5 2001/11/15 10:03:33 robbod Exp $
                                                                   -->
<!-- This file was developed by Eurostep and supplied to NIST under contract.
     Authors:
	Rob Bodington
-->
<!--                    descriptive text                           -->
<!ENTITY % desctext SYSTEM "text.ent">
%desctext;
<!ELEMENT ext_descriptions (ext_description*)>
<!ATTLIST ext_descriptions
	module_directory CDATA #REQUIRED
	schema_file CDATA #REQUIRED
        rcs.date CDATA #REQUIRED 
	rcs.revision CDATA #REQUIRED
>

<!ENTITY % description.content "%text-elts; | %block-elts; | %single-block-elts; ">
<!ELEMENT ext_description (%description.content;)*>
<!ATTLIST ext_description
	linkend CDATA #REQUIRED
>

=== starseeker/stepmod_mirror/data/modules/selected_item/mim_descriptions.xml
<?xml version="1.0"?>
<?xml-stylesheet 
  type="text/xsl" 
  href="../../../xsl/descriptions.xsl"?>
<!DOCTYPE ext_descriptions SYSTEM "../../../dtd/description.dtd">
<ext_descriptions module_directory="selected_item" schema_file="mim.xml" describe.selects="YES" rcs.date="$Date: 2003/01/09 12:10:39 $" rcs.revision="$Revision: 1.10 $">
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  Schema: Selected_item_mim
   <express_ref linkend="selected_item:mim:Selected_item_mim"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<ext_description linkend="Selected_item_mim">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Type: selected_item_context_items 
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_item_context_items"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_item_context_items">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Type: selected_item_select 
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_item_select"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_item_select">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_item  
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_item"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_item">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_item_assignment  
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_item_assignment"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_item_assignment">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_item_assignment  Attribute: assigned_class 
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_item_assignment.assigned_class"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_item_assignment.assigned_class">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_item_assignment  Attribute: items 
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_item_assignment.items"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_item_assignment.items">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_items_assignment_in_context_group  
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_items_assignment_in_context_group"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_items_assignment_in_context_group">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_items_assignment_in_context_group  Attribute: assigned_group 
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_items_assignment_in_context_group.assigned_group"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_items_assignment_in_context_group.assigned_group">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_items_assignment_in_context_group  Attribute: selected_item_assignment 
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_items_assignment_in_context_group.selected_item_assignment"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_items_assignment_in_context_group.selected_item_assignment">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_items_context_group  
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_items_context_group"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_items_context_group">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_items_context_group_to_context  
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_items_context_group_to_context"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_items_context_group_to_context">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_items_context_group_to_context  Attribute: assigned_group 
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_items_context_group_to_context.assigned_group"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_items_context_group_to_context.assigned_group">
</ext_description>
<!-- 
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   Schema: Selected_item_mim  Entity: selected_items_context_group_to_context  Attribute: item_context 
   <express_ref linkend="selected_item:mim:Selected_item_mim.selected_items_context_group_to_context.item_context"/>
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
  -->
<ext_description linkend="Selected_item_mim.selected_items_context_group_to_context.item_context">
</ext_description>
</ext_descriptions>
